---
- name:                 provision database
  become:               yes
  become_user:          '{{ seafile_user }}'
  shell:                '{{ SEAFILE_MANAGEPY }} migrate --no-input'
  environment:          '{{ SEAFILE_ENVIRONMENT }}'
  register:             seafile_syncdb
  changed_when:         seafile_syncdb.stdout.find( "Creating table ") != -1

